### ISSUE TITLE
Add the rest of the artifacts

### ISSUE THREAD

**Issue by upintheairsheep** [flamusdiu/xleapp#67]
ALEAPP, cLEAPP, RLEAPP, VLEAPP, and WLEAPP artifacts need to be added, or else this is just a fancy version of iLEAPP

**Comment by flamusdiu** [comment]
Yup, I know. I started with iLEAPP, just need to add the folders for the other ones, but each of them need to be converted and it's a slow process because there are a few hundred artifacts and I've rewritten about 50 myself. I am looking at adding some system to be able to read the old artifacts, but need to get that put togther.
